---
apiVersion: v1
kind: Namespace
metadata:
  name: kubera
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubera-auth-config
  namespace: kubera
data:
  CONFIGMAP_NAME: kubera-auth-config
  JWT_SECRET: cluster
  DB_SERVER: "mongodb://mongo-service:27017"
  DB_USER: "admin"
  DB_PASSWORD: "1234"
  PORTAL_URL: "https://kubera-core-ui:3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubera-auth-server
  namespace: kubera
spec:
  selector:
    matchLabels:
      component: kubera-auth-server
  template:
    metadata:
      labels:
        component: kubera-auth-server
    spec:
      containers:
        - name: auth-server
          image: mayadataio/kubera-auth:ci
          envFrom:
            - configMapRef:
                name: kubera-auth-config
          env:
            - name: ADMIN_USERNAME
              value: "admin"
            - name: ADMIN_PASSWORD
              value: "kubera"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      serviceAccountName: kubera-svc-account
---
apiVersion: v1
kind: Service
metadata:
  name: kubera-auth-server-service
  namespace: kubera
spec:
  type: NodePort
  ports:
    - name: auth-server
      port: 9003
      targetPort: 3000
      nodePort: 32000
  selector:
    component: kubera-auth-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: kubera
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      component: auth-database
  template:
    metadata:
      labels:
        component: auth-database
    spec:
      containers:
        - name: mongo
          image: mongo:4.4.1
          ports:
            - containerPort: 27017
          imagePullPolicy: Always
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kubera-auth-config
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kubera-auth-config
                  key: DB_PASSWORD
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: kubera
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-service
  namespace: kubera
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    component: auth-database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubera-svc-account
  namespace: kubera
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubera-rb
  namespace: kubera
subjects:
  - kind: ServiceAccount
    name: kubera-svc-account
    namespace: kubera
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
