// nolint
package types

// define the type of authorization request
const (
	JWTSecretString      = "JWT_SECRET"
	GITHUB_CLIENT_ID     = "GITHUB_CLIENT_ID"
	GITHUB_CLIENT_SECRET = "GITHUB_CLIENT_SECRET"
	GOOGLE_CLIENT_ID     = "GOOGLE_CLIENT_ID"
	GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET"
	DISABLE_LOCALAUTH    = "DISABLE_LOCALAUTH"
	DISABLE_GITHUBAUTH   = "DISABLE_GITHUBAUTH"
	DISABLE_GOOGLEAUTH   = "DISABLE_GOOGLEAUTH"
	BEARER               = "Bearer"
)
